### ISSUE TITLE
showyourwork does not work with strict channel priorities

### ISSUE THREAD

**Issue by rodluger** [showyourwork/showyourwork#232]
All `showyourwork=0.4.0` builds failing (on my machine at least) with

```
Creating conda environment /opt/anaconda3/envs/showyourwork/lib/python3.9/site-packages/showyourwork/workflow/envs/environment.yml...
Downloading and installing remote packages.
CreateCondaEnvironmentException:
Could not create conda environment from /opt/anaconda3/envs/showyourwork/lib/python3.9/site-packages/showyourwork/workflow/envs/environment.yml:
Command:
conda env create --quiet --file "/Users/luger/src/showyourwork/CoveringYourBasis/.snakemake/conda/6a8974cd927695d4e9c41504818e2677_.yaml" --prefix "/Users/luger/src/showyourwork/CoveringYourBasis/.snakemake/conda/6a8974cd927695d4e9c41504818e2677_"
Output:
Collecting package metadata (repodata.json): ...working... done
Solving environment: ...working... 
Building graph of deps:   0%|          | 0/7 [00:00<?, ?it/s]
Examining @/osx-64::__unix==0=0:   0%|          | 0/7 [00:00<?, ?it/s]
Examining conda-forge::python=3.9:  14%|█▍        | 1/7 [00:00<00:00, 1145.36it/s]
Examining @/osx-64::__osx==10.16=0:  29%|██▊       | 2/7 [00:00<00:01,  4.31it/s] 
Examining @/osx-64::__osx==10.16=0:  43%|████▎     | 3/7 [00:00<00:00,  6.46it/s]
Examining conda-forge::python-graphviz=0.20.1:  43%|████▎     | 3/7 [00:00<00:00,  6.46it/s]
Examining @/osx-64::__archspec==1=x86_64:  57%|█████▋    | 4/7 [00:00<00:00,  6.46it/s]     
Examining conda-forge::imagemagick=7.1.0.43:  71%|███████▏  | 5/7 [00:00<00:00,  6.46it/s]
Examining conda-forge::tectonic=0.11.0:  86%|████████▌ | 6/7 [00:00<00:00,  6.46it/s]     
                                                                                     

Determining conflicts:   0%|          | 0/7 [00:00<?, ?it/s]
Examining conflict for python python-graphviz:   0%|          | 0/7 [00:00<?, ?it/s]
Examining conflict for imagemagick python python-graphviz:  14%|█▍        | 1/7 [00:00<00:00, 3387.97it/s]
Examining conflict for imagemagick python tectonic python-graphviz:  29%|██▊       | 2/7 [00:00<00:00, 12.42it/s]
Examining conflict for imagemagick python tectonic python-graphviz:  43%|████▎     | 3/7 [00:00<00:00, 18.61it/s]
Examining conflict for python tectonic python-graphviz:  43%|████▎     | 3/7 [00:00<00:00, 18.61it/s]            
Examining conflict for python tectonic:  57%|█████▋    | 4/7 [00:00<00:00, 18.61it/s]                
Examining conflict for python tectonic:  71%|███████▏  | 5/7 [00:00<00:00,  8.61it/s]
Examining conflict for imagemagick tectonic python-graphviz:  71%|███████▏  | 5/7 [00:00<00:00,  8.61it/s]
Examining conflict for imagemagick python-graphviz:  86%|████████▌ | 6/7 [00:00<00:00,  8.61it/s]         
Examining conflict for imagemagick python-graphviz: 100%|██████████| 7/7 [00:00<00:00,  8.70it/s]
Examining conflict for imagemagick tectonic: 100%|██████████| 7/7 [00:01<00:00,  8.70it/s]       
Examining conflict for imagemagick tectonic: : 8it [00:01,  5.01it/s]                     
                                                                     
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed
Solving environment: ...working... 
Building graph of deps:   0%|          | 0/7 [00:00<?, ?it/s]
Examining @/osx-64::__unix==0=0:   0%|          | 0/7 [00:00<?, ?it/s]
Examining conda-forge::python=3.9:  14%|█▍        | 1/7 [00:00<00:00, 6413.31it/s]
Examining @/osx-64::__osx==10.16=0:  29%|██▊       | 2/7 [00:00<00:01,  4.78it/s] 
Examining @/osx-64::__osx==10.16=0:  43%|████▎     | 3/7 [00:00<00:00,  7.18it/s]
Examining conda-forge::python-graphviz=0.20.1:  43%|████▎     | 3/7 [00:00<00:00,  7.18it/s]
Examining @/osx-64::__archspec==1=x86_64:  57%|█████▋    | 4/7 [00:00<00:00,  7.18it/s]     
Examining conda-forge::imagemagick=7.1.0.43:  71%|███████▏  | 5/7 [00:00<00:00,  7.18it/s]
Examining conda-forge::tectonic=0.11.0:  86%|████████▌ | 6/7 [00:00<00:00,  7.18it/s]     
                                                                                     

Determining conflicts:   0%|          | 0/7 [00:00<?, ?it/s]
Examining conflict for python python-graphviz:   0%|          | 0/7 [00:00<?, ?it/s]
Examining conflict for imagemagick python python-graphviz:  14%|█▍        | 1/7 [00:00<00:00, 4185.93it/s]
Examining conflict for imagemagick python tectonic python-graphviz:  29%|██▊       | 2/7 [00:00<00:00, 12.43it/s]
Examining conflict for imagemagick python tectonic python-graphviz:  43%|████▎     | 3/7 [00:00<00:00, 18.63it/s]
Examining conflict for python tectonic python-graphviz:  43%|████▎     | 3/7 [00:00<00:00, 18.63it/s]            
Examining conflict for python tectonic:  57%|█████▋    | 4/7 [00:00<00:00, 18.63it/s]                
Examining conflict for python tectonic:  71%|███████▏  | 5/7 [00:00<00:00,  8.46it/s]
Examining conflict for imagemagick tectonic python-graphviz:  71%|███████▏  | 5/7 [00:00<00:00,  8.46it/s]
Examining conflict for imagemagick python-graphviz:  86%|████████▌ | 6/7 [00:00<00:00,  8.46it/s]         
Examining conflict for imagemagick python-graphviz: 100%|██████████| 7/7 [00:00<00:00,  8.48it/s]
Examining conflict for imagemagick tectonic: 100%|██████████| 7/7 [00:01<00:00,  8.48it/s]       
Examining conflict for imagemagick tectonic: : 8it [00:01,  4.90it/s]                     
                                                                     
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed

UnsatisfiableError: The following specifications were found to be incompatible with each other:

Output in format: Requested package -> Available versions

Package libffi conflicts for:
conda-forge::imagemagick=7.1.0.43 -> libglib[version='>=2.70.2,<3.0a0'] -> libffi[version='>=3.4,<4.0a0|>=3.4.2,<3.5.0a0']
conda-forge::tectonic=0.11.0 -> libglib[version='>=2.74.0,<3.0a0'] -> libffi[version='>=3.4,<4.0a0']
conda-forge::python=3.9 -> libffi[version='>=3.2.1,<3.3.0a0|>=3.3,<3.4.0a0|>=3.4.2,<3.5.0a0']
conda-forge::python-graphviz=0.20.1 -> python[version='>=3'] -> libffi[version='3.2.*|>=3.2.1,<3.3a0|>=3.3,<3.4.0a0|>=3.4.2,<3.5.0a0|>=3.2.1,<3.3.0a0']
conda-forge::python=3.9 -> pypy3.9=7.3.9 -> libffi[version='>=3.4,<4.0a0']

Package cairo conflicts for:
conda-forge::tectonic=0.11.0 -> harfbuzz[version='>=5.2.0,<6.0a0'] -> cairo[version='>=1.16.0,<2.0.0a0|>=1.16.0,<2.0a0']
conda-forge::imagemagick=7.1.0.43 -> graphviz[version='>=5.0.0,<6.0a0'] -> cairo[version='>=1.16.0,<2.0.0a0|>=1.16.0,<2.0a0']
conda-forge::python-graphviz=0.20.1 -> graphviz[version='>=2.46.1'] -> cairo[version='>=1.16.0,<2.0.0a0|>=1.16.0,<2.0a0']

Package freetype conflicts for:
conda-forge::imagemagick=7.1.0.43 -> freetype[version='>=2.10.4,<3.0a0']
conda-forge::imagemagick=7.1.0.43 -> fontconfig[version='>=2.13.96,<3.0a0'] -> freetype[version='>=2.12.1,<3.0a0']

Package openssl conflicts for:
conda-forge::python=3.9 -> openssl[version='>=1.1.1h,<1.1.2a|>=1.1.1i,<1.1.2a|>=1.1.1j,<1.1.2a|>=1.1.1k,<1.1.2a|>=1.1.1l,<1.1.2a|>=1.1.1n,<1.1.2a|>=1.1.1o,<1.1.2a|>=3.0.3,<4.0a0|>=3.0.2,<4.0a0|>=3.0.0,<4.0a0']
conda-forge::tectonic=0.11.0 -> openssl[version='>=1.1.1q,<1.1.2a|>=3.0.5,<4.0a0']
conda-forge::python=3.9 -> pypy3.9=7.3.9 -> openssl[version='>=1.1.1q,<1.1.2a|>=3.0.5,<4.0a0']
conda-forge::python-graphviz=0.20.1 -> python[version='>=3'] -> openssl[version='1.0.*|>=1.0.2m,<1.0.3a|>=1.0.2n,<1.0.3a|>=1.0.2o,<1.0.3a|>=1.1.1a,<1.1.2a|>=1.1.1b,<1.1.2a|>=1.1.1c,<1.1.2a|>=1.1.1d,<1.1.2a|>=1.1.1e,<1.1.2a|>=1.1.1g,<1.1.2a|>=1.1.1h,<1.1.2a|>=1.1.1i,<1.1.2a|>=1.1.1j,<1.1.2a|>=1.1.1k,<1.1.2a|>=1.1.1l,<1.1.2a|>=1.1.1m,<1.1.2a|>=1.1.1n,<1.1.2a|>=1.1.1q,<1.1.2a|>=1.1.1o,<1.1.2a|>=1.0.2l,<1.0.3a|>=1.0.2p,<1.0.3a|>=3.0.5,<4.0a0|>=3.0.3,<4.0a0|>=3.0.2,<4.0a0|>=3.0.0,<4.0a0|>=1.1.1f,<1.1.2a']

Package libcxx conflicts for:
conda-forge::imagemagick=7.1.0.43 -> fftw[version='>=3.3.10,<4.0a0'] -> libcxx[version='>=10.0.0|>=10.0.1|>=11.1.0|>=12.0.1|>=14.0.4|>=4.0.1|>=12.0.0|>=11.0.0']
conda-forge::imagemagick=7.1.0.43 -> libcxx[version='>=13.0.1']

Package pango conflicts for:
conda-forge::imagemagick=7.1.0.43 -> pango[version='>=1.50.8,<1.51.0a0']
conda-forge::imagemagick=7.1.0.43 -> graphviz[version='>=5.0.0,<6.0a0'] -> pango[version='>=1.50.7,<1.51.0a0|>=1.50.7,<2.0a0|>=1.50.9,<1.51.0a0']

Package python conflicts for:
conda-forge::python=3.9
conda-forge::python-graphviz=0.20.1 -> python[version='>=3']

Package bzip2 conflicts for:
conda-forge::python-graphviz=0.20.1 -> python[version='>=3'] -> bzip2[version='>=1.0.6,<2.0a0|>=1.0.8,<2.0a0']
conda-forge::python=3.9 -> bzip2[version='>=1.0.8,<2.0a0']
conda-forge::imagemagick=7.1.0.43 -> bzip2[version='>=1.0.8,<2.0a0']

Package libzlib conflicts for:
conda-forge::imagemagick=7.1.0.43 -> libzlib[version='>=1.2.12,<1.3.0a0']
conda-forge::imagemagick=7.1.0.43 -> fontconfig[version='>=2.13.96,<3.0a0'] -> libzlib[version='1.2.12|1.2.12|1.2.12|1.2.12|1.2.12|1.2.13|>=1.2.11,<1.3.0a0|>=1.2.13,<1.3.0a0',build='hfe4f2af_2|hfd90126_3|hfd90126_4|hfe4f2af_1|h6c3fc93_0']

Package libwebp-base conflicts for:
conda-forge::imagemagick=7.1.0.43 -> libwebp-base[version='>=1.2.2,<2.0a0']
conda-forge::imagemagick=7.1.0.43 -> graphviz[version='>=5.0.0,<6.0a0'] -> libwebp-base[version='1.1.0|1.1.0.*|1.2.0.*|1.2.1.*|1.2.2.*|1.2.3.*|1.2.4.*|>=1.2.3,<2.0a0|>=1.2.4,<2.0a0',build=2]

Package gtk2 conflicts for:
conda-forge::imagemagick=7.1.0.43 -> graphviz[version='>=5.0.0,<6.0a0'] -> gtk2
conda-forge::python-graphviz=0.20.1 -> graphviz[version='>=2.46.1'] -> gtk2

Package zlib conflicts for:
conda-forge::imagemagick=7.1.0.43 -> freetype[version='>=2.10.4,<3.0a0'] -> zlib[version='1.2.*|1.2.11|>=1.2.11,<1.3.0a0']
conda-forge::imagemagick=7.1.0.43 -> zlib[version='>=1.2.12,<1.3.0a0']

Package ca-certificates conflicts for:
conda-forge::tectonic=0.11.0 -> openssl[version='>=1.1.1q,<1.1.2a'] -> ca-certificates
conda-forge::python=3.9 -> openssl[version='>=3.0.3,<4.0a0'] -> ca-certificates

Package libiconv conflicts for:
conda-forge::tectonic=0.11.0 -> libglib[version='>=2.74.0,<3.0a0'] -> libiconv[version='>=1.17,<2.0a0']
conda-forge::imagemagick=7.1.0.43 -> libglib[version='>=2.70.2,<3.0a0'] -> libiconv[version='>=1.15,<2.0.0a0|>=1.15,<2.0a0|>=1.16,<2.0.0a0|>=1.17,<2.0a0|>=1.16,<2.0a0|>=1.17,<2.0.0a0']

Package libpng conflicts for:
conda-forge::imagemagick=7.1.0.43 -> libpng[version='>=1.6.37,<1.7.0a0']
conda-forge::imagemagick=7.1.0.43 -> libwebp -> libpng[version='>=1.6.32,<1.7.0a0|>=1.6.34,<1.7.0a0|>=1.6.35,<1.7.0a0|>=1.6.38,<1.7.0a0']

Package libglib conflicts for:
conda-forge::imagemagick=7.1.0.43 -> graphviz[version='>=5.0.0,<6.0a0'] -> libglib[version='>=2.72.1,<3.0a0|>=2.74.0,<3.0a0']
conda-forge::imagemagick=7.1.0.43 -> libglib[version='>=2.70.2,<3.0a0']

Package fontconfig conflicts for:
conda-forge::imagemagick=7.1.0.43 -> fontconfig[version='>=2.13.96,<3.0a0']
conda-forge::imagemagick=7.1.0.43 -> librsvg[version='>=2.54.4,<3.0a0'] -> fontconfig[version='>=2.13.1,<3.0a0|>=2.14.0,<3.0a0']

Package xz conflicts for:
conda-forge::imagemagick=7.1.0.43 -> xz[version='>=5.2.5,<5.3.0a0']
conda-forge::imagemagick=7.1.0.43 -> libtiff[version='>=4.4.0,<5.0a0'] -> xz[version='>=5.2.5,<6.0a0|>=5.2.6,<5.3.0a0|>=5.2.6,<6.0a0']
Note that strict channel priority may have removed packages required for satisfiability.
```

Looking into this!

**Comment by rodluger** [comment]
This happened, specifically, after I ran

```
conda config --set channel_priority strict
```

(as recommended by a Snakemake warning printed to the terminal). Undoing that with

```
conda config --set channel_priority false
```

fixes the build. That should be an OK workaround for the time being, but I'll look into fixing the `showyourwork` env to work with strict channel priority!

**Comment by rodluger** [comment]
@dfm I don't really know how to read that list of `conda` conflicts. Can you glean anything from it? How can we fix our env specification so that it works with strict channel priorities? Our environment file is as simple as they come:

```
dependencies:
  - conda-forge::python=3.9
  - conda-forge::tectonic=0.11.0
  - conda-forge::imagemagick=7.1.0.43
  - conda-forge::python-graphviz=0.20.1
```

**Comment by rodluger** [comment]
I think I fixed this. The trick was to explicitly make `conda-forge` a higher priority channel than `defaults`.

```
channels:
  - conda-forge
  - defaults
dependencies:
  - conda-forge::python=3.9
  - conda-forge::tectonic=0.11.0
  - conda-forge::imagemagick=7.1.0.43
  - conda-forge::python-graphviz=0.20.1
```

**Comment by rodluger** [comment]
I'll work on updating the FAQs if people still have issues -- relaxing the `channel_priority` setting is the workaround for now. It looks like conda is having [a LOT of trouble](https://github.com/conda/conda/issues/11555) with strict channel priorities, so there's probably stuff they need to fix on their end as well.

**Comment by MilesCranmer** [comment]
Oops, didn't see this! I made a PR for this here but I think it's the opposite of what we want. https://github.com/showyourwork/showyourwork-action/pull/8

For the record, my conda environment is just this:
```yml
channels:
  - conda-forge
dependencies:
  - numpy=1.19.5
  - pip=21.0.1
  - python=3.9
  - pandas=1.4.1
  - matplotlib==3.5.1
  - pip:
      - pyyaml==5.4.1
      - mpmath==1.2.1
      - openpyxl==3.0.9
```
In other words: no use of `defaults` at all. This is supposed to be more robust, and `conda-forge` has everything anyways.

**Comment by MilesCranmer** [comment]
Still getting this error in the github action, even with my attempt to fix it. Not sure why.

**Comment by rodluger** [comment]
I'll look into it. Let's continue the conversation over at https://github.com/showyourwork/showyourwork-action/pull/8.
